name = "tools-dev66"
main = "src/worker.js"
compatibility_date = "2024-05-01"
workers_dev = true
preview_urls = true

[assets]
directory = "dist"
binding = "ASSETS"
html_handling = "none"

[[routes]]
pattern = "tools.dev66.net"
custom_domain = true
